// svelte/src/components/FavoritesItem.svelte
<script lang="ts">
  import favorites from '@/stores/favorites';
  import type { ListGame } from 'rawg-api-sdk';

  export let game: ListGame;
</script>

<li class="list-group-item d-flex align-items-center">
  <img src={game.background_image} alt="Cover of {game.name}" />
  <span class="ms-2 flex-grow-1">{game.name}</span>
  <button class="btn btn-close" on:click={() => favorites.remove(game)} />
</li>

<style lang="scss">
  img {
    height: 64px;
    width: 64px;
    object-fit: cover;
  }
</style>

// react/src/components/FavoritesItem.tsx
import { ListGame } from 'rawg-api-sdk';
import { useDispatch } from 'react-redux';
import { remove as removeFromFavorites } from '../stores/favorites';
import { AppDispatch } from '../stores';
import styles from './FavoritesItem.module.scss';

type FavoritesItemProps = {
  game: ListGame;
};

function FavoritesItem({ game }: FavoritesItemProps) {
  const dispatch = useDispatch<AppDispatch>();

  return (
    <li className="list-group-item d-flex align-items-center">
      <img
        src={game.background_image}
        className={styles.cover}
        alt={`Cover of ${game.name}`}
      />
      <span className="ms-2 flex-grow-1">{game.name}</span>
      <button
        className="btn btn-close"
        onClick={() => dispatch(removeFromFavorites(game))}
      />
    </li>
  );
}

export default FavoritesItem;
