// svelte/src/components/GameCard.svelte
<script lang="ts">
  import { favorites } from '@/stores';
  import type { ListGame } from 'rawg-api-sdk';

  export let game: ListGame;

  function addToFavorites() {
    favorites.update((favorites) => [...favorites, game]);
  }
</script>

<div class="card">
  {#if game.background_image}
    <img
      src={game.background_image}
      class="card-img-top"
      alt="Cover of {game.name}"
    />
  {/if}
  <div class="card-body d-flex flex-column">
    <h5 class="card-title">{game.name}</h5>
    <h6 class="card-subtitle mb-2 text-muted flex-grow-1">
      {game.genres.map((genre) => genre.name).join('/')}
    </h6>
    <p class="card-text text-muted text-end">
      From {game.released.getFullYear()}
    </p>
    <button
      class="btn btn-primary"
      disabled={$favorites.some((g) => g.id === game.id)}
      on:click={addToFavorites}>Add to favorites</button
    >
  </div>
</div>

<style lang="scss">
  img {
    aspect-ratio: 16/9;
    object-fit: cover;
  }
</style>

// react/src/components/GameCard.tsx
import { ListGame } from 'rawg-api-sdk';
import { favoritesState } from '../stores/favorites';
import styles from './GameCard.module.scss';
import { useRecoilState } from 'recoil';

type GameCardProps = {
  game: ListGame;
};

function GameCard({ game }: GameCardProps) {
  const [favorites, setFavorites] = useRecoilState(favoritesState);

  const addToFavorites = () => setFavorites(favorites.concat(game));
  const disabled = favorites.some((fav) => fav.id === game.id);

  return (
    <div className="card">
      {game.background_image && (
        <img
          src={game.background_image}
          className={`card-img-top ${styles.cover}`}
          alt={`Cover of ${game.name}`}
        />
      )}
      <div className="card-body d-flex flex-column">
        <h5 className="card-title">{game.name}</h5>
        <h6 className="card-subtitle mb-2 text-muted flex-grow-1">
          {game.genres.map((genre) => genre.name).join('/')}
        </h6>
        <p className="card-text text-muted text-end">
          From {game.released?.getFullYear()}
        </p>
        <button
          className="btn btn-primary"
          disabled={disabled}
          onClick={addToFavorites}
        >
          Add to favorites
        </button>
      </div>
    </div>
  );
}

export default GameCard;
