// react/src/components/Favorites.tsx
import { useRecoilState } from 'recoil';
import { favoritesState } from '../stores/favorites';
import FavoritesItem from './FavoritesItem';

function Favorites() {
  const [favorites] = useRecoilState(favoritesState);

  return (
    <>
      <h2 className="text-center mt-4 mb-3">Favorites</h2>
      <ul className="list-group">
        {favorites.map((game) => (
          <FavoritesItem game={game} key={game.id} />
        ))}
        {!favorites.length && (
          <li className="list-group-item">No games favorited yet</li>
        )}
      </ul>
    </>
  );
}

export default Favorites;

// svelte/src/components/Favorites.svelte
<script lang="ts">
  import favorites from '@/stores/favorites';
  import FavoritesItem from './FavoritesItem.svelte';
</script>

<h2 class="text-center mt-4 mb-3">Favorites</h2>
<ul class="list-group">
  {#each $favorites as game (game.id)}
    <FavoritesItem {game} />
  {:else}
    <li class="list-group-item">No games favorited yet</li>
  {/each}
</ul>
