// react/src/components/SearchField.tsx
import { useDebouncedCallback } from 'use-debounce';

type SearchFieldProps = {
  onSearch: (search: string) => void;
};

function SearchField({ onSearch }: SearchFieldProps) {
  const debounced = useDebouncedCallback(onSearch, 750);

  return (
    <input
      type="text"
      className="form-control mb-3"
      placeholder="Search"
      onChange={(e) => debounced(e.target.value)}
    />
  );
}

export default SearchField;

// svelte/src/components/SearchField.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { debounce } from 'svelte-debounce';

  export let value: string = '';
  export let debounceDelay: number = 750;

  const dispatch = createEventDispatcher<{
    search: string;
  }>();

  const debounceConfig = {
    callback: () => dispatch('search', value),
    delay: debounceDelay,
  };
</script>

<input
  type="text"
  class="form-control mb-3"
  placeholder="Search"
  bind:value
  use:debounce={debounceConfig}
/>
